# Generated by Django 4.2.7 on 2023-12-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_is_offensive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='menu',
            field=models.CharField(choices=[('Discussions', 'Discussions'), ('Marketplace', 'Marketplace'), ('Connect', 'Connect'), ('Tournament', 'Tournament'), ('Beta Testing', 'Beta Testing')], default='Discussions', max_length=20),
        ),
    ]
