# Generated by Django 4.2.7 on 2023-11-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_uservisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='charisma_score',
            field=models.IntegerField(default=0),
        ),
    ]
