# Generated by Django 4.2.7 on 2024-01-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_alter_user_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="friend_suggestion_timestamp",
            field=models.DateTimeField(null=True),
        ),
    ]
